"""Persona-vectors pipeline helpers (Chen et al. 2025, arXiv:2507.21509).

Skeleton for Phase 5 D1.0+. Encodes the pinned decisions from
docs/references/activation-steering-audio-llm/notes/spike-f-persona-vectors-pipeline.md:

- Axis-as-trait modeling (3 bipolar V/A/D directions).
- Response-token mean pooling for direction extraction.
- 0-100 LLM-judge net rubric for validation.
- Cross-model judging (judge != target) to avoid self-grading bias.

I/O helpers (load/save) are fully implemented. LLM-calling functions
(elicit_*, run_target_llm, judge_response) raise NotImplementedError;
they are filled in by the D1.0 smoke-test PR with concrete provider
adapters (Anthropic, OpenAI, local llama-cpp via subprocess).
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Iterable, Iterator, Literal, Protocol


# ---------------------------------------------------------------------------
# Pinned constants (do not change without revisiting Spike F)
# ---------------------------------------------------------------------------

class Axis(str, Enum):
    VALENCE = "valence"
    AROUSAL = "arousal"
    DOMINANCE = "dominance"


class Pole(str, Enum):
    POSITIVE = "positive"
    NEGATIVE = "negative"


AXES: tuple[Axis, ...] = (Axis.VALENCE, Axis.AROUSAL, Axis.DOMINANCE)

# Per persona-vectors paper Appendix A.1.
N_POS_PROMPTS_PER_AXIS = 5
N_NEG_PROMPTS_PER_AXIS = 5
N_QUESTIONS_PER_AXIS = 40

# Per Appendix A.3: response-token averaging beats prompt-token / last-token.
PoolingStrategy = Literal["response_mean"]
DEFAULT_POOLING: PoolingStrategy = "response_mean"

# Per spike-f memo §"Concrete changes to plan documents": passes if
# steered@α=+1 net-score gap >= +15 and steered@α=-1 net-score gap <= -15.
JUDGE_PASS_THRESHOLD_POINTS = 15.0


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class TraitDescription:
    """One bipolar axis description. Loaded from data/trait_descriptions.json."""
    axis: Axis
    positive_pole: str
    negative_pole: str
    context: str


@dataclass(frozen=True)
class ContrastPair:
    """One row of contrast_pairs.jsonl.

    Generated by 02b_generate_contrast_pairs.py; consumed by
    03_extract_llm_directions.py.
    """
    axis: Axis
    pole: Pole
    system_prompt: str
    question: str

    def to_jsonl(self) -> str:
        return json.dumps(
            {
                "axis": self.axis.value,
                "pole": self.pole.value,
                "system_prompt": self.system_prompt,
                "question": self.question,
            },
            ensure_ascii=False,
        )


@dataclass(frozen=True)
class JudgeScore:
    """One LLM-judge rating. 0-100 net (positive_pole_score - negative_pole_score)."""
    axis: Axis
    response: str
    positive_pole_score: float
    negative_pole_score: float

    @property
    def net(self) -> float:
        return self.positive_pole_score - self.negative_pole_score


# ---------------------------------------------------------------------------
# Provider abstractions (filled in by D1.0)
# ---------------------------------------------------------------------------

class ElicitationLLM(Protocol):
    """LLM that drafts contrast prompts. Used once, offline, archived."""
    def complete(self, system: str, user: str) -> str: ...


class TargetLLM(Protocol):
    """The frozen LLM whose directions we are extracting.

    Conceptually wraps the existing crates/core/src/nodes/llama_cpp/
    activation extractor; called via subprocess from Python in the D1.0
    implementation. Returns hidden-state vectors at a given layer,
    pooled over response tokens only.
    """
    def generate_and_pool_response(
        self,
        system_prompt: str,
        question: str,
        layer: int,
        pooling: PoolingStrategy = DEFAULT_POOLING,
    ) -> "list[float]":  # n_embd-dim vector
        ...


class JudgeLLM(Protocol):
    """LLM scoring response trait expression on a 0-100 scale.

    MUST be a different model than TargetLLM (avoid self-grading bias).
    Per paper Appendix B: 94.7% agreement with human raters in their setup.
    """
    def score(self, axis: Axis, pole: Pole, response: str, trait_description: TraitDescription) -> float: ...


# ---------------------------------------------------------------------------
# I/O helpers (fully implemented)
# ---------------------------------------------------------------------------

def load_trait_descriptions(path: Path) -> dict[Axis, TraitDescription]:
    """Load trait_descriptions.json and validate the axis-as-trait schema."""
    with path.open("r", encoding="utf-8") as f:
        raw = json.load(f)

    out: dict[Axis, TraitDescription] = {}
    for axis in AXES:
        block = raw.get(axis.value)
        if block is None:
            raise ValueError(f"trait_descriptions.json missing required axis: {axis.value}")
        for required in ("positive_pole", "negative_pole", "context"):
            if required not in block or not isinstance(block[required], str) or not block[required].strip():
                raise ValueError(f"trait_descriptions.json axis '{axis.value}' missing/empty field: {required}")
        out[axis] = TraitDescription(
            axis=axis,
            positive_pole=block["positive_pole"],
            negative_pole=block["negative_pole"],
            context=block["context"],
        )
    return out


def load_contrast_pairs(path: Path) -> Iterator[ContrastPair]:
    """Stream contrast_pairs.jsonl one row at a time (~600 rows; fits in memory but stream by default)."""
    with path.open("r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
                yield ContrastPair(
                    axis=Axis(row["axis"]),
                    pole=Pole(row["pole"]),
                    system_prompt=row["system_prompt"],
                    question=row["question"],
                )
            except (KeyError, ValueError, TypeError) as exc:
                raise ValueError(f"contrast_pairs.jsonl line {line_no}: {exc}") from exc


def dump_contrast_pairs(pairs: Iterable[ContrastPair], path: Path) -> int:
    """Write contrast pairs to JSONL; returns row count."""
    n = 0
    with path.open("w", encoding="utf-8") as f:
        for pair in pairs:
            f.write(pair.to_jsonl())
            f.write("\n")
            n += 1
    return n


# ---------------------------------------------------------------------------
# Pipeline stages (skeletons; implementations land in D1.0)
# ---------------------------------------------------------------------------

def elicit_contrast_prompts_for_axis(
    trait: TraitDescription,
    elicitation_llm: ElicitationLLM,
    n_pos: int = N_POS_PROMPTS_PER_AXIS,
    n_neg: int = N_NEG_PROMPTS_PER_AXIS,
    n_questions: int = N_QUESTIONS_PER_AXIS,
) -> Iterator[ContrastPair]:
    """Generate n_pos*n_questions positive + n_neg*n_questions negative pairs for one axis.

    Persona-vectors pipeline (paper App. A.1 / App. D template). For each
    axis, makes 3 elicitation calls:

      1. n_pos system prompts that induce the *positive* pole.
      2. n_neg system prompts that induce the *negative* pole.
      3. n_questions evaluation questions that surface the trait.

    The cartesian product (system_prompt × question) per pole is the
    contrast set: n_pos × n_questions positive pairs + n_neg × n_questions
    negative pairs.

    Each elicitation response is parsed as a numbered line list; the
    parser tolerates `1.`, `1)`, `- `, leading whitespace, and blank lines.
    """
    pos_prompts = _elicit_lines(
        elicitation_llm,
        system=_SYSTEM_PROMPT_AUTHOR,
        user=_user_for_pole_prompts(trait, Pole.POSITIVE, n_pos),
        expected_count=n_pos,
    )
    neg_prompts = _elicit_lines(
        elicitation_llm,
        system=_SYSTEM_PROMPT_AUTHOR,
        user=_user_for_pole_prompts(trait, Pole.NEGATIVE, n_neg),
        expected_count=n_neg,
    )
    questions = _elicit_lines(
        elicitation_llm,
        system=_QUESTION_AUTHOR,
        user=_user_for_questions(trait, n_questions),
        expected_count=n_questions,
    )

    for sp in pos_prompts:
        for q in questions:
            yield ContrastPair(axis=trait.axis, pole=Pole.POSITIVE, system_prompt=sp, question=q)
    for sp in neg_prompts:
        for q in questions:
            yield ContrastPair(axis=trait.axis, pole=Pole.NEGATIVE, system_prompt=sp, question=q)


# ---------------------------------------------------------------------------
# Elicitation prompt templates (paper App. A.1 / App. D, adapted)
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT_AUTHOR = (
    "You are an expert prompt engineer designing system prompts for a controlled "
    "experiment on a frozen LLM. The experiment measures how strongly a target "
    "trait is expressed when the model is steered toward one pole of a "
    "Valence/Arousal/Dominance axis. Your job is to write a varied set of system "
    "prompts that induce the requested pole behaviorally — without changing the "
    "underlying assistant's helpfulness."
)

_QUESTION_AUTHOR = (
    "You are an expert prompt engineer designing evaluation questions for a "
    "controlled experiment on a frozen LLM. Your questions should be neutral, "
    "open-ended, and conversational so that any tonal differences in the response "
    "are attributable to the model's persona rather than the question's content."
)


def _user_for_pole_prompts(trait: TraitDescription, pole: Pole, n: int) -> str:
    pole_text = trait.positive_pole if pole == Pole.POSITIVE else trait.negative_pole
    return (
        f"Axis: {trait.axis.value} ({pole.value} pole)\n"
        f"Pole description:\n{pole_text}\n\n"
        f"Context:\n{trait.context}\n\n"
        f"Write exactly {n} distinct system prompts that induce the {pole.value} "
        f"pole of {trait.axis.value}. Each prompt should:\n"
        f"  - vary in phrasing and angle (different metaphors, different tone hints),\n"
        f"  - induce the pole through tone/cadence/stance, not by changing facts,\n"
        f"  - be 1-3 sentences, written as instructions to a helpful assistant.\n\n"
        f"Output a numbered list. One prompt per line. No commentary, no headers."
    )


def _user_for_questions(trait: TraitDescription, n: int) -> str:
    return (
        f"Axis: {trait.axis.value}\n"
        f"Positive-pole description:\n{trait.positive_pole}\n\n"
        f"Negative-pole description:\n{trait.negative_pole}\n\n"
        f"Context:\n{trait.context}\n\n"
        f"Write exactly {n} short evaluation questions that, when posed to an "
        f"assistant, would let a judge tell apart responses on the {trait.axis.value} "
        f"axis. Questions should:\n"
        f"  - be neutral and open-ended (not leading toward either pole),\n"
        f"  - be conversational (a user might naturally ask them),\n"
        f"  - vary in topic so the contrast set is broad.\n\n"
        f"Output a numbered list. One question per line. No commentary, no headers."
    )


def _elicit_lines(
    elicitation_llm: "ElicitationLLM",
    *,
    system: str,
    user: str,
    expected_count: int,
) -> list[str]:
    """Call the elicitation LLM and parse its response as a list of lines.

    Tolerates `1.`, `1)`, `- `, `* `, and leading whitespace. Drops blank
    lines. Returns at most `expected_count` lines (truncates over-eager
    output).
    """
    import re

    text = elicitation_llm.complete(system, user)
    lines: list[str] = []
    for raw in text.splitlines():
        s = raw.strip()
        if not s:
            continue
        # Strip numbering / bullets: "1.", "1)", "- ", "* "
        s = re.sub(r"^\s*(?:\d+[\.\)]|[-*])\s*", "", s).strip()
        if not s:
            continue
        lines.append(s)
    if len(lines) < expected_count:
        raise ValueError(
            f"elicitation produced {len(lines)} usable lines; "
            f"expected {expected_count}. Raw text:\n{text}"
        )
    return lines[:expected_count]


def extract_axis_direction(
    contrast_pairs: Iterable[ContrastPair],
    target_llm: TargetLLM,
    layer: int,
    axis: Axis,
    pooling: PoolingStrategy = DEFAULT_POOLING,
) -> "list[float]":
    """Compute v_axis = mean(positive activations) - mean(negative activations).

    See IMPLEMENTATION_PLAN §4.5 + Spike F memo for the protocol.
    """
    import numpy as np  # local import keeps the public Protocol typing-only

    import sys as _sys

    pos_acts: list[list[float]] = []
    neg_acts: list[list[float]] = []
    n_seen = 0
    for pair in contrast_pairs:
        if pair.axis != axis:
            continue
        vec = target_llm.generate_and_pool_response(
            pair.system_prompt, pair.question, layer, pooling
        )
        if pair.pole == Pole.POSITIVE:
            pos_acts.append(vec)
        else:
            neg_acts.append(vec)
        n_seen += 1
        if n_seen % 50 == 0:
            print(
                f"    extract {axis.value} {n_seen} pairs  "
                f"(pos={len(pos_acts)}, neg={len(neg_acts)})",
                file=_sys.stderr, flush=True,
            )

    if not pos_acts or not neg_acts:
        raise ValueError(
            f"extract_axis_direction({axis.value}): "
            f"need at least one positive and one negative pair; "
            f"got n_pos={len(pos_acts)} n_neg={len(neg_acts)}"
        )

    pos_mean = np.mean(np.asarray(pos_acts, dtype=np.float32), axis=0)
    neg_mean = np.mean(np.asarray(neg_acts, dtype=np.float32), axis=0)
    return (pos_mean - neg_mean).astype(np.float32).tolist()


def judge_steered_responses(
    responses_unsteered: list[str],
    responses_steered_pos: list[str],
    responses_steered_neg: list[str],
    axis: Axis,
    trait_description: TraitDescription,
    judge_llm: JudgeLLM,
) -> dict[str, float]:
    """0-100 net rubric per IMPLEMENTATION_PLAN §4.6.

    For each response, ask the judge for a positive_pole score and a
    negative_pole score (both 0-100). Net = pos - neg. Then mean over the
    batch per condition.

    Returns dict with keys:
        net_unsteered, net_steered_pos, net_steered_neg,
        gap_pos (= net_steered_pos - net_unsteered),
        gap_neg (= net_steered_neg - net_unsteered).

    Pass criterion (caller checks): gap_pos >= JUDGE_PASS_THRESHOLD_POINTS and
                                    gap_neg <= -JUDGE_PASS_THRESHOLD_POINTS.
    """

    import sys as _sys

    def _net_mean(responses: list[str], label: str) -> float:
        if not responses:
            return 0.0
        nets: list[float] = []
        for i, r in enumerate(responses):
            if not r:
                # Empty string = degenerate generation (likely bailed at the
                # first audio token). Skip; don't penalize the axis for an
                # MLX modality glitch.
                continue
            pos = judge_llm.score(axis, Pole.POSITIVE, r, trait_description)
            neg = judge_llm.score(axis, Pole.NEGATIVE, r, trait_description)
            nets.append(pos - neg)
            if (i + 1) % 10 == 0:
                print(
                    f"    judge {axis.value} {label} {i + 1}/{len(responses)}",
                    file=_sys.stderr, flush=True,
                )
        if not nets:
            return 0.0
        return float(sum(nets) / len(nets))

    net_u = _net_mean(responses_unsteered, "unsteered")
    net_p = _net_mean(responses_steered_pos, "+alpha")
    net_n = _net_mean(responses_steered_neg, "-alpha")

    return {
        "net_unsteered": net_u,
        "net_steered_pos": net_p,
        "net_steered_neg": net_n,
        "gap_pos": net_p - net_u,
        "gap_neg": net_n - net_u,
    }


# ---------------------------------------------------------------------------
# Smoke-test entry point (Qwen3-7B; gates D1.3+)
# ---------------------------------------------------------------------------

@dataclass
class SmokeTestResult:
    """Output of the D1.0 prerequisite smoke test (PROJECT_PLAN §10 R9)."""
    model_name: str
    layer: int
    per_axis: dict[Axis, dict[str, float]] = field(default_factory=dict)
    passed: bool = False
    failure_reason: str | None = None

    def axis_passed(self, axis: Axis) -> bool:
        block = self.per_axis.get(axis, {})
        return (
            block.get("gap_pos", 0.0) >= JUDGE_PASS_THRESHOLD_POINTS
            and block.get("gap_neg", 0.0) <= -JUDGE_PASS_THRESHOLD_POINTS
        )
